resources:
  - monitor.yaml

# Uncomment the metrics-with-certificates patch in
# config/default/kustomization.yaml as well.
#patches:
#  - path: monitor_tls_patch.yaml
#    target:
#      kind: ServiceMonitor
