{{- range $name, $controller := .Values.controllers }}
{{- if $controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: temporal-{{ $name }}-controller-metrics
  namespace: {{ include "temporal-platform-operator.namespace" $ }}
  labels:
    {{- include "temporal-platform-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-controller
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "temporal-platform-operator.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "temporal-platform-operator.fullname" $ }}-{{ $name }}-metrics-auth
  labels:
    {{- include "temporal-platform-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs: [create]
  - apiGroups: [authorization.k8s.io]
    resources: [subjectaccessreviews]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "temporal-platform-operator.fullname" $ }}-{{ $name }}-metrics-auth
  labels:
    {{- include "temporal-platform-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "temporal-platform-operator.fullname" $ }}-{{ $name }}-metrics-auth
subjects:
  - kind: ServiceAccount
    name: {{ include "temporal-platform-operator.fullname" $ }}-{{ $name }}
    namespace: {{ include "temporal-platform-operator.namespace" $ }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "temporal-platform-operator.fullname" $ }}-{{ $name }}-metrics-reader
  labels:
    {{- include "temporal-platform-operator.labels" $ | nindent 4 }}
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: [get]
---
{{- end }}
{{- end }}
