apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal-platform-operator.serviceAccountName" . }}
  namespace: {{ include "temporal-platform-operator.namespace" . }}
  labels:
    {{- include "temporal-platform-operator.labels" . | nindent 4 }}
