{{- range $name, $controller := .Values.controllers }}
{{- if $controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal-platform-operator.fullname" $ }}-{{ $name }}
  namespace: {{ include "temporal-platform-operator.namespace" $ }}
  labels:
    {{- include "temporal-platform-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-controller
---
{{- end }}
{{- end }}
