---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - temporal.io
    resources:
      - workerdeployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - temporal.nori-cloud.io
    resources:
      - temporalnamespaces
      - temporalproxies
      - temporalworkers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - temporal.nori-cloud.io
    resources:
      - temporalnamespaces/finalizers
      - temporalproxies/finalizers
      - temporalworkers/finalizers
    verbs:
      - update
  - apiGroups:
      - temporal.nori-cloud.io
    resources:
      - temporalnamespaces/status
      - temporalproxies/status
      - temporalworkers/status
    verbs:
      - get
      - patch
      - update
