apiVersion: temporal.nori-cloud.io/v1alpha1
kind: TemporalNamespace
metadata:
  labels:
    app.kubernetes.io/name: temporal-platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: temporalnamespace-sample
spec:
  retentionDays: 7
